// PRD §16.3 GEOGRAPHY REFERENCE / PROFILE + P2.5's "real reference data"
// requirement: ~400 skills across the nine §11.5.3 functional areas, ~80
// industries with adjacency, ~150 interests, ~60 languages.

// Names whose punctuation-stripped slug would otherwise collide
// (e.g. "C++" and "C#" both reduce to "c").
const SLUG_OVERRIDES: Record<string, string> = {
  "C++": "cpp",
  "C#": "csharp",
};

function slugify(name: string): string {
  if (SLUG_OVERRIDES[name]) return SLUG_OVERRIDES[name];
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// PRD §11.5.3: "engineering, data/ML, design, product, growth/marketing,
// sales/BD, finance, ops, legal."
export const FUNCTIONAL_AREAS = [
  "engineering",
  "data",
  "design",
  "product",
  "growth",
  "sales",
  "finance",
  "ops",
  "legal",
] as const;
export type FunctionalArea = (typeof FUNCTIONAL_AREAS)[number];

const SKILLS_BY_AREA: Record<FunctionalArea, string[]> = {
  engineering: [
    "JavaScript",
    "TypeScript",
    "Python",
    "Java",
    "C++",
    "C#",
    "Go",
    "Rust",
    "Ruby",
    "PHP",
    "Swift",
    "Kotlin",
    "React",
    "Vue.js",
    "Angular",
    "Node.js",
    "Express.js",
    "Next.js",
    "Django",
    "Flask",
    "Spring Boot",
    ".NET",
    "GraphQL",
    "REST APIs",
    "Microservices",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "Google Cloud Platform",
    "Terraform",
    "CI/CD",
    "Git",
    "Linux",
    "Bash Scripting",
    "SQL",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "Elasticsearch",
    "Apache Kafka",
    "RabbitMQ",
    "System Design",
    "Distributed Systems",
    "Software Architecture",
    "Unit Testing",
    "Test-Driven Development",
    "Web Security",
    "Mobile Development",
    "iOS Development",
    "Android Development",
    "Embedded Systems",
    "WebAssembly",
    "GraphQL Federation",
    "gRPC",
    "Serverless Architecture",
  ],
  data: [
    "Python for Data Science",
    "R",
    "SQL for Analytics",
    "Pandas",
    "NumPy",
    "Scikit-learn",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Data Visualization",
    "Tableau",
    "Power BI",
    "Data Warehousing",
    "ETL Pipelines",
    "Apache Spark",
    "Hadoop",
    "Statistics",
    "A/B Testing",
    "Machine Learning",
    "Deep Learning",
    "Natural Language Processing",
    "Computer Vision",
    "Reinforcement Learning",
    "Feature Engineering",
    "Model Deployment",
    "MLOps",
    "Data Engineering",
    "Big Data",
    "Data Mining",
    "Predictive Modeling",
    "Time Series Analysis",
    "Bayesian Statistics",
    "Data Governance",
    "dbt",
    "Snowflake",
    "BigQuery",
    "Databricks",
    "Apache Airflow",
    "Data Storytelling",
    "Experimentation Design",
    "Causal Inference",
    "Recommender Systems",
    "Anomaly Detection",
    "Generative AI",
    "Prompt Engineering",
    "LLM Fine-tuning",
  ],
  design: [
    "UI Design",
    "UX Design",
    "Figma",
    "Sketch",
    "Adobe XD",
    "Prototyping",
    "Wireframing",
    "User Research",
    "Usability Testing",
    "Interaction Design",
    "Visual Design",
    "Design Systems",
    "Typography",
    "Illustration",
    "Motion Design",
    "Graphic Design",
    "Brand Identity",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Adobe After Effects",
    "Information Architecture",
    "Accessibility Design",
    "Design Thinking",
    "User Personas",
    "Journey Mapping",
    "Responsive Design",
    "Design Critique",
    "Component Libraries",
    "Icon Design",
    "3D Design",
    "Game Design",
    "Print Design",
    "Packaging Design",
    "Service Design",
    "Product Design",
    "Design Ops",
    "Color Theory",
    "Layout Design",
    "Web Design",
    "Sound Design",
    "Design Research",
  ],
  product: [
    "Product Management",
    "Product Strategy",
    "Roadmapping",
    "User Stories",
    "Agile",
    "Scrum",
    "Kanban",
    "Product Analytics",
    "Product Discovery",
    "Prioritization Frameworks",
    "Stakeholder Management",
    "Go-to-Market Strategy",
    "Product Launch",
    "Competitive Analysis",
    "Customer Interviews",
    "Product Requirements Documents",
    "OKRs",
    "Growth Strategy",
    "Product-Market Fit",
    "Feature Prioritization",
    "Product Marketing",
    "Pricing Strategy",
    "User Onboarding",
    "Retention Strategy",
    "Product Vision",
    "Backlog Management",
    "Cross-functional Leadership",
    "Product Metrics",
    "Technical Product Management",
    "API Product Management",
    "Platform Strategy",
    "B2B Product Management",
    "B2C Product Management",
    "Product Operations",
    "Voice of Customer",
    "Jira",
    "Product Positioning",
    "Vendor Management for Product",
  ],
  growth: [
    "SEO",
    "SEM",
    "Content Marketing",
    "Social Media Marketing",
    "Email Marketing",
    "Growth Hacking",
    "Marketing Analytics",
    "Brand Marketing",
    "Performance Marketing",
    "Influencer Marketing",
    "Marketing Automation",
    "Copywriting",
    "Conversion Rate Optimization",
    "Google Analytics",
    "Google Ads",
    "Meta Ads",
    "Marketing Strategy",
    "Public Relations",
    "Community Management",
    "Affiliate Marketing",
    "Video Marketing",
    "Podcast Marketing",
    "Marketing Funnels",
    "Demand Generation",
    "Account-Based Marketing",
    "Marketing Campaigns",
    "Growth Marketing",
    "User Acquisition",
    "Referral Marketing",
    "CRM Marketing",
    "HubSpot",
    "Marketo",
    "Mailchimp",
    "Landing Page Optimization",
    "Viral Marketing",
    "Brand Storytelling",
    "PR Strategy",
    "Event Marketing",
    "Guerrilla Marketing",
    "Marketing Research",
    "Localization Marketing",
  ],
  sales: [
    "Sales Strategy",
    "B2B Sales",
    "B2C Sales",
    "Cold Calling",
    "Cold Emailing",
    "Sales Negotiation",
    "Account Management",
    "Business Development",
    "Partnership Development",
    "Salesforce",
    "HubSpot CRM",
    "Lead Generation",
    "Sales Pipeline Management",
    "Enterprise Sales",
    "SaaS Sales",
    "Sales Forecasting",
    "Solution Selling",
    "Consultative Selling",
    "Channel Sales",
    "Sales Operations",
    "Sales Enablement",
    "Customer Success",
    "Key Account Management",
    "Commercial Contract Negotiation",
    "Deal Structuring",
    "Territory Management",
    "Sales Coaching",
    "Inside Sales",
    "Outside Sales",
    "Sales Analytics",
    "Pipeline Forecasting",
    "Prospecting",
    "Objection Handling",
    "Relationship Building",
    "Strategic Partnerships",
    "Channel Partnerships",
    "Sales Presentations",
    "RFP Management",
    "International Sales",
    "Sales Training",
  ],
  finance: [
    "Financial Modeling",
    "Financial Analysis",
    "Budgeting",
    "Forecasting",
    "Valuation",
    "Corporate Finance",
    "Investment Analysis",
    "Financial Planning",
    "Accounting",
    "Bookkeeping",
    "Tax Planning",
    "Audit",
    "Risk Management",
    "Cash Flow Management",
    "Financial Reporting",
    "Excel Modeling",
    "Venture Capital",
    "Private Equity",
    "Fundraising",
    "Cap Table Management",
    "Financial Due Diligence",
    "Mergers & Acquisitions",
    "Cost Accounting",
    "Management Accounting",
    "Treasury Management",
    "Payroll",
    "Financial Statement Analysis",
    "Equity Research",
    "Credit Analysis",
    "Portfolio Management",
    "Financial Strategy",
    "Unit Economics",
    "Pricing Analysis",
    "Revenue Recognition",
    "GAAP",
    "IFRS",
    "QuickBooks",
    "SAP Finance",
    "Financial Compliance",
    "FP&A",
  ],
  ops: [
    "Operations Management",
    "Project Management",
    "Program Management",
    "Process Improvement",
    "Supply Chain Management",
    "Logistics",
    "Inventory Management",
    "Vendor Management",
    "Six Sigma",
    "Lean Management",
    "Business Process Optimization",
    "Quality Assurance",
    "Quality Management",
    "Facilities Management",
    "Procurement",
    "Change Management",
    "Operational Risk Management",
    "Compliance Operations",
    "Business Continuity Planning",
    "Resource Planning",
    "Operational Excellence",
    "Workforce Planning",
    "HR Operations",
    "Recruiting",
    "People Operations",
    "Onboarding Programs",
    "Performance Management",
    "Employee Engagement",
    "Office Management",
    "Event Planning",
    "Customer Support Operations",
    "IT Operations",
    "Data Operations",
    "Scheduling",
    "Capacity Planning",
    "Cross-functional Coordination",
    "KPI Tracking",
    "Standard Operating Procedures",
    "Business Analysis",
    "Automation",
  ],
  legal: [
    "Contract Law",
    "Contract Negotiation",
    "Corporate Law",
    "Intellectual Property Law",
    "Compliance",
    "Regulatory Affairs",
    "Employment Law",
    "Data Privacy Law",
    "GDPR Compliance",
    "Legal Research",
    "Legal Writing",
    "Litigation",
    "Mergers & Acquisitions Law",
    "Securities Law",
    "Trademark Law",
    "Patent Law",
    "Copyright Law",
    "Contract Drafting",
    "Due Diligence",
    "Legal Risk Assessment",
    "Corporate Governance",
    "Legal Operations",
    "Immigration Law",
    "Tax Law",
    "International Law",
    "Arbitration",
    "Mediation",
    "Legal Compliance Training",
    "Privacy Policy Drafting",
    "Terms of Service Drafting",
    "Legal Technology",
    "Antitrust Law",
    "Consumer Protection Law",
    "Real Estate Law",
    "Bankruptcy Law",
    "Employment Contracts",
    "NDAs",
    "Licensing Agreements",
    "Legal Advisory",
  ],
};

export type SkillSeed = {
  name: string;
  slug: string;
  functionalArea: FunctionalArea;
  aliases: string[];
};

export const SKILLS: SkillSeed[] = FUNCTIONAL_AREAS.flatMap((area) =>
  SKILLS_BY_AREA[area].map((name) => ({
    name,
    slug: slugify(name),
    functionalArea: area,
    aliases: [],
  })),
);

// A handful of real alias mappings (BR-PROF-02: "ReactJS" -> "React").
const ALIASES: Record<string, string[]> = {
  React: ["ReactJS", "React.js"],
  "Vue.js": ["VueJS", "Vue"],
  "Node.js": ["NodeJS", "Node"],
  JavaScript: ["JS"],
  TypeScript: ["TS"],
  "Google Cloud Platform": ["GCP"],
  PostgreSQL: ["Postgres"],
  "Machine Learning": ["ML"],
  "Natural Language Processing": ["NLP"],
  "Search Engine Optimization": ["SEO"],
};
for (const skill of SKILLS) {
  const aliases = ALIASES[skill.name];
  if (aliases) skill.aliases = aliases;
}

// ~80 industries. Adjacency is expressed as slugs of related industries
// (self-referencing INT[] in the DB; resolved to ids at insert time).
export type IndustrySeed = { name: string; slug: string; adjacentSlugs: string[] };

const INDUSTRY_GROUPS: Record<string, string[]> = {
  tech: [
    "Software",
    "SaaS",
    "Cloud Computing",
    "Enterprise Software",
    "Artificial Intelligence",
    "Cybersecurity",
    "Data & Analytics",
    "Developer Tools",
    "Open Source",
    "Consumer Electronics",
    "Semiconductor",
    "Robotics",
    "Space Technology",
    "Web3",
    "Blockchain",
  ],
  fintech: [
    "FinTech",
    "Banking",
    "Insurance",
    "InsurTech",
    "Investment Management",
    "Venture Capital",
    "Private Equity",
    "Payments",
    "Wealth Management",
    "Cryptocurrency Exchanges",
  ],
  commerce: [
    "E-commerce",
    "Retail",
    "Marketplace Platforms",
    "Direct-to-Consumer",
    "Wholesale Distribution",
    "Fashion",
    "Luxury Goods",
    "Consumer Packaged Goods",
  ],
  health: [
    "HealthTech",
    "Biotechnology",
    "Pharmaceuticals",
    "Medical Devices",
    "Healthcare Services",
    "Digital Health",
    "Mental Health Services",
    "Fitness & Wellness",
    "Telemedicine",
  ],
  media: [
    "Media & Entertainment",
    "Gaming",
    "Esports",
    "Music",
    "Film & TV",
    "Publishing",
    "News Media",
    "Social Media",
    "Advertising",
    "Marketing Technology",
  ],
  industrial: [
    "Manufacturing",
    "Automotive",
    "Aerospace",
    "Construction",
    "Real Estate",
    "PropTech",
    "Logistics & Supply Chain",
    "Transportation",
    "Energy",
    "Renewable Energy",
    "Oil & Gas",
    "Mining",
    "Utilities",
    "Chemicals",
  ],
  services: [
    "Consulting",
    "Legal Services",
    "Accounting Services",
    "Human Resources",
    "Recruiting",
    "Staffing",
    "Education Services",
    "Higher Education",
    "K-12 Education",
    "Vocational Training",
    "Research & Development",
  ],
  other: [
    "Travel & Hospitality",
    "Food & Beverage",
    "Agriculture",
    "AgTech",
    "Nonprofit & NGO",
    "Government",
    "Public Sector",
    "Defense",
    "Environmental Services",
    "Waste Management",
    "Telecommunications",
  ],
};

export const INDUSTRIES: IndustrySeed[] = Object.entries(INDUSTRY_GROUPS).flatMap(
  ([group, names]) =>
    names.map((name) => ({
      name,
      slug: slugify(name),
      // Adjacent = other members of the same broad group (excluding self).
      adjacentSlugs: names
        .filter((n) => n !== name)
        .map(slugify)
        .slice(0, 8),
    })),
);

// ~150 interests spanning professional, creative, athletic and community life.
export const INTERESTS: string[] = [
  "Reading",
  "Writing",
  "Blogging",
  "Photography",
  "Videography",
  "Travel",
  "Hiking",
  "Running",
  "Cycling",
  "Swimming",
  "Yoga",
  "Meditation",
  "Cooking",
  "Baking",
  "Wine Tasting",
  "Coffee Culture",
  "Craft Beer",
  "Gaming",
  "Board Games",
  "Chess",
  "Music Production",
  "Playing Guitar",
  "Playing Piano",
  "Singing",
  "Painting",
  "Drawing",
  "Sculpture",
  "Pottery",
  "Gardening",
  "Home Improvement",
  "DIY Projects",
  "Woodworking",
  "Cars",
  "Motorcycles",
  "Fitness",
  "Weightlifting",
  "Rock Climbing",
  "Surfing",
  "Skiing",
  "Snowboarding",
  "Football",
  "Basketball",
  "Cricket",
  "Tennis",
  "Badminton",
  "Golf",
  "Volleyball",
  "Table Tennis",
  "Martial Arts",
  "Dance",
  "Theater",
  "Film",
  "Anime",
  "Comics",
  "Podcasts",
  "Stand-up Comedy",
  "Astronomy",
  "History",
  "Philosophy",
  "Psychology",
  "Politics",
  "Economics",
  "Science Fiction",
  "Fantasy Literature",
  "Poetry",
  "Learning Languages",
  "Volunteering",
  "Mentoring",
  "Public Speaking",
  "Debate",
  "Investing",
  "Cryptocurrency",
  "Personal Finance",
  "Real Estate Investing",
  "Startups",
  "Entrepreneurship",
  "Angel Investing",
  "Open Source Contribution",
  "Robotics",
  "3D Printing",
  "Drones",
  "Sustainability",
  "Environmentalism",
  "Veganism",
  "Wildlife Conservation",
  "Animal Welfare",
  "Pet Care",
  "Fashion",
  "Interior Design",
  "Architecture",
  "Urban Planning",
  "Travel Photography",
  "Street Photography",
  "Portrait Photography",
  "Food Blogging",
  "Wine Making",
  "Home Brewing",
  "Camping",
  "Fishing",
  "Sailing",
  "Scuba Diving",
  "Kayaking",
  "Paragliding",
  "Skydiving",
  "Marathon Running",
  "Triathlon",
  "CrossFit",
  "Pilates",
  "Tai Chi",
  "Calligraphy",
  "Origami",
  "Knitting",
  "Sewing",
  "Jewelry Making",
  "Collecting Vinyl Records",
  "Collecting Watches",
  "Collecting Sneakers",
  "Vintage Cars",
  "Model Building",
  "Puzzle Solving",
  "Trivia",
  "Escape Rooms",
  "Karaoke",
  "DJing",
  "Music Festivals",
  "Concerts",
  "Museums",
  "Art Galleries",
  "Wine Clubs",
  "Book Clubs",
  "Volunteering Abroad",
  "Teaching",
  "Coaching",
  "Life Coaching",
  "Mentorship Programs",
  "Networking Events",
  "Hackathons",
  "Chess Tournaments",
  "Fantasy Sports",
  "Sports Analytics",
  "Stock Market Analysis",
  "Blockchain Technology",
  "NFTs",
  "Space Exploration",
  "Climate Technology",
  "Social Impact",
  "Diversity & Inclusion",
  "Mental Health Advocacy",
  "LGBTQ+ Advocacy",
  "Women in Tech",
  "Community Organizing",
  "Skateboarding",
  "Bouldering",
  "Frisbee",
  "Ultimate Frisbee",
  "Archery",
];

// ~60 languages (ISO 639-1 where one exists).
export const LANGUAGES: { code: string; name: string }[] = [
  { code: "en", name: "English" },
  { code: "hi", name: "Hindi" },
  { code: "bn", name: "Bengali" },
  { code: "te", name: "Telugu" },
  { code: "mr", name: "Marathi" },
  { code: "ta", name: "Tamil" },
  { code: "ur", name: "Urdu" },
  { code: "gu", name: "Gujarati" },
  { code: "kn", name: "Kannada" },
  { code: "ml", name: "Malayalam" },
  { code: "pa", name: "Punjabi" },
  { code: "or", name: "Odia" },
  { code: "as", name: "Assamese" },
  { code: "mai", name: "Maithili" },
  { code: "sa", name: "Sanskrit" },
  { code: "ks", name: "Kashmiri" },
  { code: "kok", name: "Konkani" },
  { code: "sd", name: "Sindhi" },
  { code: "ne", name: "Nepali" },
  { code: "mni", name: "Manipuri" },
  { code: "brx", name: "Bodo" },
  { code: "sat", name: "Santali" },
  { code: "doi", name: "Dogri" },
  { code: "fr", name: "French" },
  { code: "es", name: "Spanish" },
  { code: "de", name: "German" },
  { code: "it", name: "Italian" },
  { code: "pt", name: "Portuguese" },
  { code: "nl", name: "Dutch" },
  { code: "ru", name: "Russian" },
  { code: "zh", name: "Mandarin Chinese" },
  { code: "yue", name: "Cantonese" },
  { code: "ja", name: "Japanese" },
  { code: "ko", name: "Korean" },
  { code: "vi", name: "Vietnamese" },
  { code: "th", name: "Thai" },
  { code: "id", name: "Indonesian" },
  { code: "ms", name: "Malay" },
  { code: "tl", name: "Filipino" },
  { code: "ar", name: "Arabic" },
  { code: "he", name: "Hebrew" },
  { code: "tr", name: "Turkish" },
  { code: "fa", name: "Persian" },
  { code: "sw", name: "Swahili" },
  { code: "am", name: "Amharic" },
  { code: "zu", name: "Zulu" },
  { code: "af", name: "Afrikaans" },
  { code: "pl", name: "Polish" },
  { code: "uk", name: "Ukrainian" },
  { code: "ro", name: "Romanian" },
  { code: "el", name: "Greek" },
  { code: "cs", name: "Czech" },
  { code: "hu", name: "Hungarian" },
  { code: "sv", name: "Swedish" },
  { code: "no", name: "Norwegian" },
  { code: "da", name: "Danish" },
  { code: "fi", name: "Finnish" },
  { code: "is", name: "Icelandic" },
  { code: "ha", name: "Hausa" },
  { code: "yo", name: "Yoruba" },
  { code: "ig", name: "Igbo" },
];
